### ISSUE TITLE
New-SCEPmanClone syntax error - Unexpected token ')' in expression or statement.

### ISSUE THREAD

**Issue by pmontanaro** [scepman/scepman-psmodule#53]
Running the `New-SCEPmanClone` cmdlet causes the detection of App Service settings from source to fail, resulting in misconfiguration of the cloned target App Service. 

The following error occurs:
![Screen Shot 2023-04-28 at 3 47 27 pm](https://user-images.githubusercontent.com/24598782/235065142-91f545b3-7762-4a2c-8c1a-8aad5f53c521.png)

Resulting in 0 slot settings being cloned to the new app service.

**Comment by bb-froggy** [comment]
Hi @pmontanaro, thanks for reporting this!

I see in the screenshot that this was SCEPman module version 1.10.1. This should be fixed in the latest version with commit 1d7e8a7. There was an additional incompatibility on Linux for New-SCEPmanClone, but this is now also fixed.

To ensure you are using the latest version (currently 1.11.6), execute
```
Remove-Module SCEPman
Install-Module SCEPman -Force -Scope CurrentUser
```
